export const WORD_BANKS = {
    english: [
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
        "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
        "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
        "an", "will", "my", "one", "all", "would", "there", "their", "what",
        "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
        "when", "make", "can", "like", "time", "no", "just", "him", "know",
        "take", "people", "into", "year", "your", "good", "some", "could",
        "them", "see", "other", "than", "then", "now", "look", "only", "come",
        "its", "over", "think", "also", "back", "after", "use", "two", "how",
        "our", "work", "first", "well", "way", "even", "new", "want", "because",
        "any", "these", "give", "day", "most", "us", "is", "are", "was", "were",
        "has", "had", "been", "will", "shall", "should", "would", "can", "could",
        "may", "might", "must", "am", "do", "does", "did", "need", "try", "find",
        "create", "build", "develop", "code", "program", "debug", "compile", "run",
        "walk", "talk", "hear", "listen", "write", "read", "speak", "learn", "teach",
        "study", "understand", "remember", "forget", "think", "believe", "hope",
        "feel", "love", "hate", "like", "dislike", "enjoy", "prefer", "want",
        "wish", "need", "desire", "expect", "plan", "decide", "choose", "select",
        "take", "give", "offer", "accept", "refuse", "reject", "receive", "get",
        "obtain", "acquire", "lose", "miss", "drop", "fall", "rise", "stand",
        "sit", "lie", "sleep", "wake", "dream", "eat", "drink", "cook", "bake",
        "boil", "fry", "grill", "roast", "buy", "sell", "pay", "spend", "save",
        "earn", "invest", "borrow", "lend", "owe", "own", "possess", "belong",
        "go", "come", "arrive", "depart", "leave", "stay", "remain", "return",
        "enter", "exit", "visit", "travel", "journey", "voyage", "fly", "drive",
        "ride", "sail", "swim", "run", "jog", "sprint", "climb", "jump", "hop",
        "world", "life", "hand", "part", "child", "eye", "woman", "place", "work",
        "week", "case", "point", "government", "company", "number", "group", "problem",
        "fact", "idea", "water", "room", "mother", "area", "money", "story", "young",
        "fact", "month", "lot", "right", "study", "book", "eye", "job", "word",
        "business", "issue", "side", "kind", "head", "house", "service", "friend",
        "father", "power", "hour", "game", "line", "end", "member", "law", "car",
        "city", "community", "name", "president", "team", "minute", "best", "several",
        "body", "information", "nothing", "ago", "lead", "social", "understand", "whether",
        "watch", "together", "follow", "around", "parent", "stop", "face", "anything",
        "black", "already", "course", "white", "start", "state", "school", "much",
        "least", "example", "family", "moment", "rather", "sound", "master", "once",
        "voice", "whole", "matter", "stand", "early", "between", "change", "help",
        "line", "own", "show", "large", "often", "real", "set", "such", "best",
        "place", "where", "ask", "house", "show", "again", "point", "call", "try",
        "ask", "need", "too", "feel", "become", "leave", "put", "mean", "keep",
        "student", "why", "let", "great", "same", "big", "group", "begin", "seem",
        "country", "help", "talk", "where", "turn", "problem", "every", "start",
        "hand", "might", "American", "show", "part", "about", "against", "place",
        "over", "such", "again", "few", "case", "most", "week", "company", "where",
        "system", "each", "right", "program", "hear", "so", "question", "during",
        "work", "play", "government", "run", "small", "number", "off", "always",
        "move", "like", "night", "live", "Mr", "point", "believe", "hold", "today",
        "bring", "happen", "next", "without", "before", "large", "million", "must",
        "home", "under", "water", "room", "write", "mother", "area", "national",
        "money", "story", "young", "fact", "month", "different", "lot", "right",
        "study", "book", "eye", "job", "word", "though", "business", "issue",
        "side", "kind", "four", "head", "far", "black", "long", "both", "little",
        "house", "yes", "after", "since", "long", "provide", "service", "around",
        "friend", "important", "father", "sit", "away", "until", "power", "hour",
        "game", "often", "yet", "line", "political", "end", "among", "ever",
        "stand", "bad", "lose", "however", "member", "pay", "law", "meet", "car",
        "city", "almost", "include", "continue", "set", "later", "community",
        "much", "name", "five", "once", "white", "least", "president", "learn",
        "real", "change", "team", "minute", "best", "several", "idea", "kid",
        "body", "information", "nothing", "ago", "right", "lead", "social",
        "understand", "whether", "back", "watch", "together", "follow", "around",
        "parent", "only", "stop", "face", "anything", "create", "public",
        "already", "speak", "others", "read", "level", "allow", "add", "office",
        "spend", "door", "health", "person", "art", "sure", "such", "war", "history",
        "party", "within", "grow", "result", "open", "change", "morning", "walk",
        "reason", "low", "win", "research", "girl", "guy", "early", "food",
        "before", "moment", "himself", "air", "teacher", "force", "offer",
        "enough", "both", "education", "across", "although", "remember", "foot",
        "second", "boy", "maybe", "toward", "able", "age", "off", "policy",
        "everything", "love", "process", "music", "including", "consider",
        "appear", "actually", "buy", "probably", "human", "wait", "serve",
        "market", "die", "send", "expect", "home", "sense", "build", "stay",
        "fall", "oh", "nation", "plan", "cut", "college", "interest", "death",
        "course", "someone", "experience", "behind", "reach", "local", "kill",
        "six", "remain", "effect", "use", "yeah", "suggest", "class", "control",
        "raise", "care", "perhaps", "little", "late", "hard", "field", "else",
        "pass", "former", "sell", "major", "sometimes", "require", "along",
        "development", "themselves", "report", "role", "better", "economic",
        "effort", "up", "decide", "rate", "strong", "possible", "heart", "drug",
        "show", "leader", "light", "voice", "wife", "whole", "police", "mind",
        "finally", "pull", "return", "free", "military", "price", "report",
        "less", "according", "decision", "explain", "son", "hope", "even",
        "develop", "view", "relationship", "carry", "town", "road", "drive",
        "arm", "true", "federal", "break", "better", "difference", "thank",
        "receive", "value", "international", "building", "action", "full",
        "model", "join", "season", "society", "because", "tax", "director",
        "early", "position", "player", "agree", "especially", "record", "pick",
        "wear", "paper", "special", "space", "ground", "form", "support",
        "event", "official", "whose", "matter", "everyone", "center", "couple",
        "site", "end", "project", "hit", "base", "activity", "star", "table",
        "need", "court", "produce", "eat", "American", "teach", "oil", "half",
        "situation", "easy", "cost", "industry", "figure", "face", "street",
        "image", "itself", "phone", "either", "data", "cover", "quite", "picture",
        "clear", "practice", "piece", "land", "recent", "describe", "product",
        "doctor", "wall", "patient", "worker", "news", "test", "movie", "certain",
        "north", "love", "personal", "open", "support", "simply", "third",
        "technology", "catch", "step", "baby", "computer", "type", "attention",
        "draw", "film", "Republican", "tree", "source", "red", "nearly",
        "organization", "choose", "cause", "hair", "look", "point", "century",
        "evidence", "window", "difficult", "listen", "soon", "culture",
        "billion", "chance", "brother", "energy", "period", "course", "summer",
        "less", "realize", "hundred", "available", "plant", "likely", "opportunity",
        "term", "short", "letter", "condition", "choice", "place", "single",
        "rule", "daughter", "administration", "south", "husband", "Congress",
        "floor", "campaign", "material", "population", "well", "call", "economy",
        "medical", "hospital", "church", "close", "thousand", "risk", "current",
        "fire", "future", "wrong", "involve", "defense", "anyone", "increase",
        "security", "bank", "myself", "certainly", "west", "sport", "board",
        "seek", "per", "subject", "officer", "private", "rest", "behavior",
        "deal", "performance", "fight", "throw", "top", "past", "goal", "second",
        "bed", "order", "author", "blood", "upon", "agency", "push", "nature",
        "color", "no", "recently", "store", "reduce", "sound", "note", "fine",
        "near", "movement", "page", "enter", "share", "than", "common", "poor",
        "other", "natural", "race", "concern", "series", "significant",
        "similar", "hot", "language", "each", "usually", "response", "dead",
        "rise", "animal", "factor", "decade", "article", "shoot", "east", "save",
        "seven", "artist", "away", "scene", "stock", "career", "despite",
        "central", "eight", "thus", "treatment", "beyond", "happy", "exactly",
        "protect", "approach", "lie", "size", "dog", "fund", "serious", "occur",
        "media", "ready", "sign", "thought", "list", "individual", "simple",
        "quality", "pressure", "accept", "answer", "hard", "resource", "identify",
        "left", "meeting", "determine", "prepare", "disease", "whatever", "success",
        "argue", "cup", "particularly", "amount", "ability", "staff", "recognize",
        "indicate", "character", "growth", "loss", "degree", "wonder", "attack",
        "herself", "region", "television", "box", "TV", "training", "pretty",
        "trade", "deal", "election", "everybody", "physical", "lay", "general",
        "feeling", "standard", "bill", "message", "fail", "outside", "arrive",
        "analysis", "benefit", "name", "sex", "forward", "lawyer", "present",
        "section", "environmental", "glass", "answer", "skill", "sister", "PM",
        "professor", "operation", "financial", "crime", "stage", "ok", "compare",
        "authority", "miss", "design", "sort", "one", "act", "ten", "knowledge",
        "gun", "station", "blue", "state", "strategy", "little", "clearly",
        "discuss", "indeed", "force", "truth", "song", "example", "democratic",
        "check", "environment", "leg", "dark", "public", "various", "rather",
        "laugh", "guess", "executive", "set", "study", "prove", "hang", "entire",
        "rock", "design", "enough", "forget", "since", "claim", "note", "remove",
        "manager", "help", "close", "sound", "enjoy", "network", "legal",
        "religious", "cold", "form", "final", "main", "science", "green",
        "memory", "card", "above", "seat", "cell", "establish", "nice", "trial",
        "expert", "that", "spring", "firm", "Democrat", "radio", "visit",
        "management", "care", "avoid", "imagine", "tonight", "huge", "ball",
        "no", "close", "finish", "yourself", "talk", "theory", "impact",
        "respond", "statement", "maintain", "charge", "popular", "traditional",
        "onto", "reveal", "direction", "weapon", "employee", "cultural",
        "contain", "peace", "head", "control", "base", "pain", "apply", "play",
        "measure", "wide", "shake", "fly", "interview", "manage", "chair",
        "fish", "particular", "camera", "structure", "politics", "perform",
        "bit", "weight", "suddenly", "discover", "candidate", "top",
        "production", "treat", "trip", "evening", "affect", "inside",
        "conference", "unit", "best", "style", "adult", "worry", "range",
        "mention", "rather", "far", "deep", "front", "edge", "individual",
        "specific", "writer", "trouble", "necessary", "throughout",
        "challenge", "fear", "shoulder", "institution", "middle", "sea",
        "dream", "bar", "beautiful", "property", "instead", "improve", "stuff",
        "claim"
    ],
    indonesian: [
        "aku", "kamu", "dan", "yang", "untuk", "dengan", "bisa", "ini", "itu",
        "mereka", "kita", "belajar", "coding", "makan", "tidur", "berjalan",
        "cepat", "lambat", "hujan", "panas", "dingin", "adalah", "dari", "akan",
        "sudah", "juga", "sangat", "hanya", "ada", "tidak", "dapat", "lebih",
        "saya", "dia", "sama", "kata", "kerja", "buku", "rumah", "sekolah",
        "pergi", "datang", "pulang", "masuk", "keluar", "atas", "bawah", "kiri",
        "kanan", "depan", "belakang", "dalam", "luar", "besar", "kecil", "tinggi",
        "rendah", "panjang", "pendek", "jauh", "dekat", "lama", "baru", "tua",
        "muda", "mahal", "murah", "baik", "buruk", "bagus", "jelek", "benar",
        "salah", "buka", "tutup", "nyala", "mati", "hidup", "mati", "mulai",
        "selesai", "pagi", "siang", "sore", "malam", "hari", "minggu", "bulan",
        "tahun", "waktu", "jam", "menit", "detik", "kemarin", "besok", "lusa",
        "sekarang", "nanti", "tadi", "kapan", "dimana", "siapa", "apa", "kenapa",
        "bagaimana", "mengapa", "berapa", "karena", "tetapi", "namun", "walaupun",
        "meskipun", "jika", "kalau", "biar", "agar", "supaya", "dan", "atau",
        "serta", "lalu", "kemudian", "maka", "jadi", "karena", "sebab", "oleh",
        "tentang", "kepada", "bagi", "guna", "buat", "paling", "terlalu", "kurang",
        "cukup", "sekali", "sering", "jarang", "selalu", "kadang", "pernah", "belum",
        "sedang", "masih", "akan", "telah", "ingin", "mau", "harus", "wajib",
        "boleh", "mungkin", "pasti", "tentu", "yakin", "percaya", "tahu", "mengerti",
        "paham", "ingat", "lupa", "lihat", "dengar", "rasa", "cium", "raba",
        "pegang", "ambil", "taruh", "simpan", "buang", "cari", "temu", "hilang",
        "jatuh", "naik", "turun", "maju", "mundur", "pindah", "diam", "jalan",
        "lari", "lompat", "duduk", "berdiri", "baring", "senyum", "tawa", "tangis",
        "marah", "sedih", "senang", "bahagia", "cinta", "sayang", "benci", "rindu",
        "harap", "doa", "mimpi", "cita", "usaha", "hasil", "sukses", "gagal",
        "menang", "kalah", "juara", "teman", "sahabat", "musuh", "lawan", "saudara",
        "keluarga", "ayah", "ibu", "kakak", "adik", "anak", "suami", "istri",
        "kakek", "nenek", "paman", "bibi", "sepupu", "ipar", "mertua", "menantu",
        "guru", "murid", "siswa", "mahasiswa", "dosen", "dokter", "perawat", "polisi",
        "tentara", "pilot", "supir", "petani", "nelayan", "pedagang", "pengusaha", "penulis",
        "langit", "bumi", "matahari", "bulan", "bintang", "awan", "angin", "udara",
        "api", "air", "tanah", "batu", "pasir", "laut", "sungai", "danau",
        "gunung", "bukit", "hutan", "pohon", "bunga", "buah", "daun", "akar",
        "hewan", "binatang", "burung", "ikan", "kucing", "anjing", "ayam", "bebek",
        "sapi", "kambing", "kuda", "gajah", "mobil", "motor", "sepeda", "bus",
        "kereta", "pesawat", "kapal", "perahu", "meja", "kursi", "lemari", "pintu",
        "jendela", "kaca", "lantai", "atap", "dinding", "pagar", "taman", "lapangan",
        "pasar", "toko", "warung", "kantor", "pabrik", "gedung", "jalan", "jembatan",
        "kota", "desa", "negara", "benua", "dunia", "akhirat", "surga", "neraka",
        "agama", "tuhan", "malaikat", "ibadah", "doa", "puasa", "zakat", "haji",
        "sedekah", "infak", "masjid", "gereja", "pura", "wihara", "klenteng",
        "hari", "senin", "selasa", "rabu", "kamis", "jumat", "sabtu", "minggu",
        "januari", "februari", "maret", "april", "mei", "juni", "juli", "agustus",
        "september", "oktober", "november", "desember", "merah", "kuning", "hijau",
        "biru", "hitam", "putih", "abu", "coklat", "ungu", "nila", "jingga", "emas",
        "perak", "perunggu", "besi", "baja", "tembaga", "timah", "nikel", "seng",
        "alumunium", "plastik", "karet", "kayu", "kertas", "kain", "benang", "jarum",
        "gunting", "pisau", "sendok", "garpu", "piring", "gelas", "mangkuk", "cangkir",
        "botol", "ember", "sapu", "pel", "sikat", "sabun", "sampo", "odol", "sikat",
        "handuk", "baju", "celana", "rok", "jas", "jaket", "topi", "sepatu", "sandal",
        "kaos", "kemeja", "dasi", "tas", "dompet", "uang", "kartu", "kunci", "gembok",
        "lampu", "listrik", "kabel", "baterai", "sinyal", "internet", "wifi", "kuota",
        "pulsa", "nomor", "telepon", "hp", "laptop", "komputer", "mouse", "keyboard",
        "layar", "monitor", "printer", "speaker", "kamera", "foto", "video", "film",
        "lagu", "musik", "nada", "suara", "bunyi", "sepi", "ramai", "sunyi", "bising",
        "gaduh", "tenang", "damai", "aman", "nyaman", "kacau", "rusak", "hancur",
        "pecah", "retak", "putus", "sambung", "tempel", "ikat", "bungkus", "buka",
        "tutup", "geser", "dorong", "tarik", "tekan", "putar", "injak", "lompat",
        "terbang", "melayang", "jatuh", "tenggelam", "apung", "hanyut", "renang",
        "selam", "mandi", "cuci", "jemur", "lipat", "setrika", "masak", "goreng",
        "rebus", "bakar", "panggang", "potong", "iris", "cincang", "giling", "aduk",
        "campur", "saring", "tuang", "minum", "telan", "kunyah", "hisap", "tiup",
        "bau", "wangi", "harum", "busuk", "amis", "apek", "anyir", "asam", "manis",
        "pahit", "asin", "pedas", "tawar", "gurih", "lezat", "enak", "sedap",
        "nikmat", "puas", "kenyang", "lapar", "haus", "dahaga", "lelah", "capek",
        "letih", "lesu", "lemah", "kuat", "sehat", "sakit", "sembuh", "obat",
        "dokter", "suntik", "infus", "operasi", "lukis", "gambar", "warna", "cat",
        "kuas", "kanvas", "tulis", "baca", "hitung", "hapus", "garis", "titik",
        "koma", "tanya", "seru", "tanda", "huruf", "angka", "nomor", "abjad",
        "eja", "baca", "pustaka"
    ]
}
